# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: sis
  pool: 5
  username: root
  password: 

test:
  adapter: mysql
  database: library_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  #database: sis_dev
  database: sisparii_db
  pool: 5
  username: root
  #password: PasswordAshia@2021
  password: aY[y9)tPpOwa@2021

